<h2>TERMS AND CONDITIONS</h2>
<ul> 
<li>Activation of the Member's account or use of services provided by Shipville, LLC(hereinafter "Shipville.com") will represent the Member's acceptance of this agreement (hereinafter "Agreement"), as set forth in the following Terms and Conditions, and the Member's authorization for Shipville.com to charge the Member's credit card for all future charges.</li>
<li>Shipville.com reserves the right, at its sole discretion, to change, modify, or otherwise alter these terms and conditions. It is the Member's responsibility to review the Shipville.com Terms and Conditions periodically as continued use of Shipville.com's services will constitute the Member's acceptance of any revised terms and conditions.</li>
<li>Shipville.com prohibits any illegal activity by its Members. Any charges incurred, legal or otherwise, by Shipville.com in connection with the enforcement of the law against a Member or a potential Member will be the financial responsibility of the Member or the potential Member. See Indemnification section below for further details.</li>
<li>Membership starts the day the Member's application is received by Shipville.com. Shipville.com cannot send any shipments until all required documentation is received, including but not limited to a notarized USPS Mail Forwarding Form 1583 for Premium+Mail Members.</li></ul>
 
<h2>I. TERMS OF SERVICE</h2>

<ul><li>Shipville.com will provide the Member with an address in the U.S.A. to which the Member can have mail and/or merchandise delivered.</li>
<li>Shipville.com's services consist of receiving the Member's merchandise, which will be sorted, packed, and shipped to the Member's specified local address</li>
<li>All packages received by Shipville.com will be opened by representatives of the company. Members are responsible for all import obligations in the country to which all mail (for a +Mail Member only) and packages will be shipped.</li>
<li>For +Mail Members, Shipville.com also will receive the Member's mail (i.e., letters, catalogs, magazines, and newspapers), Shipville.com cannot hold or store mail that will not fit into a 4 inch-tall mailbox. Shipville.com will notify the Member via e-mail once his/her mailbox is full, and the Member will have 5 days to either (a) request shipment of the mail or (b) request that MyUS.com discard the mail. If no reply is received from the Member, Shipville.com will ship the mail to the Member's address on record. Any charges generated directly from this activity, including taxes, customs duties, and service charges (including any charges that may be established in the future) will be the responsibility of the Member.</li>
<li>The Member authorizes Shipville.com to charge his/her credit card for all services and/or account activity with Shipville.com. Such charges may include but are not limited to membership dues, shipping and handling charges, storage charges, late charges, and any optional services. Failure to provide payment for services rendered at the time of service may result in late charges, stop shipment charges, suspension of service, cancellation of membership, and involuntary return or the discarding of any remaining merchandise.</li>
<li>Shipping charges are based on weight, although dimensional charges may be used for bulky, lightweight packages.</li>
<li>Shipville.com will allow active Premium and +Mail Members to store their merchandise for up to 30 days at no charge. Shipville.com will allow active Standard Members to store their merchandise for up to 5 days at no charge. After 30 days for Premium and +Mail Members, or after 5 days for Standard Members, the Member agrees to pay storage charges of USD $1 per box per day.</li>
<li>Prohibited or restricted merchandise is not storable and will be rejected, destroyed, or provided to government officials.</li>
<li>Insurance costs for shipments of merchandise is based on the insured value. All insured shipments receive USD $100 of insurance, which is included in the shipping costs. Each additional USD $100 of insured value costs USD $2 USD. The insured value is subject to the terms and conditions of the particular carrier's airway bill(s). All claims are reviewed individually and any claim payment will be based on the declared value.</li>
<li>Claims for lost or damaged merchandise must be filed within the published time limits of the particular carrier. Claims are considered filed when a fully completed claim form, photograph(s), and supporting documentation, including receipts, are received by Shipville.com. Claims are reviewed individually and the review process will take a minimum of eight (8) weeks. Specific commodities, including televisions, computers, electronics, jewelry, figurines, furniture and lighting have limits of liability in case of loss or damage regardless of the declared value or insurance costs paid. Any liability for damage or loss caused after delivery to Shipville.com is limited to the lesser of either the declared value, proof of purchase price, or the specific commodity liability limit. No liability will be assumed by Shipville.com for damage or loss caused to any items before delivery to Shipville.com or caused to merchandise prepackaged by manufacturer.  Failure to file a completed claim within the carrier time limit will invalidate the claim.</li>
<li>Either party may cancel the Membership Agreement with written notice (via email, fax or letter). Upon cancellation, Shipville.com Members will receive a prorated refund on the unused portion of their annual membership charge. Annual membership refunds are based on the monthly membership usage rate of USD $19.99 per month for a +Mail Membership and USD $9.99 for a Premium Membership. Refunds will be processed within ten (10) business days of cancellation.</li>
<li>Shipville.com will have the option of returning all packages/mail to the sender(s) and/or of discarding the items for any reason.</li>
<li>Monthly membership charges, setup charges and magazine purchases are non-refundable. Shipping charges for non-members or cancelled customers are twice the rate of the shipping charges listed on the Shipville website.</li>
<li>If a Member's account charges become delinquent for more than 30 days, Shipville.com may, at its sole discretion, cancel the Member's membership, process all packages and mail by returning the same to the sender, or discarding all packages and mail. The Member forfeits all claims to items abandoned in his/her mailbox once the membership is cancelled.</li>
<li>Monthly and annual memberships are automatically renewed unless the Member advises Shipville.com in writing the he/she wishes not to renew his/her membership.</li>
<li>There is no membership fee for a Standard Account. Charges of a Standard Account only are incurred for initial set up, processing, shipping, and other shipping-related services.</li>
<li>Each package received by Shipville.com with an incomplete, incorrect, or old address that can be associated with a Member will be assessed a USD $5 charge. Members should ensure that all merchants and sellers ship all packages with the complete and accurate address, including the Member's unique suite number. All packages received with incomplete, incorrect, or old addresses that cannot be associated with a Member will be returned to the Sender or discarded.</li>
<li>All invoices past due for more than thirty (30) days will be assessed USD $10 plus a 5% per month late charge. Personal Shopper orders past due for more than fifteen (15) days will be assessed USD $10 plus a 5% late charge for each 15 day period that an order remains past due.</li></ul>
 
<h2>II. COMPLIANCE WITH LAWS</h2>
<ul>
<li>The Member is responsible for and warrants his/her compliance with all applicable laws, rules and regulations, including, but not limited to, the import and export laws and government regulations of any country to, from, through or over which the Member's shipment may be carried. This responsibility includes determining and meeting any and all applicable import and export obligations and license requirements, including those of the U.S. Department of Commerce, U.S. Department of State, U.S. Customs and Border Protection, U.S. Department of Treasury, and any and all import obligations or license requirements of the destination country. The Member agrees and acknowledges that he/she shall purchase any and all merchandise from United States sellers under an ex-works agreement.</li>
<li>The Member agrees to furnish the necessary information and complete and attach the necessary documents to comply with any applicable laws, rules and/or regulations, including notifying the United States Principal Party In Interest ("USPPI"ù), as defined by the United States Foreign Trade Regulations in every transaction generated by the Member. The Member agrees to provide to MyUS.com all required information for export purposes from the United States Principal Party in Interest, including without limitation the Export Control Classification Number and the USPPI's tax identification number (if an Electronic Export Information filing (‚ÄúEEI‚Äù) via the Automated Export System (‚ÄúAES‚Äù) is required.</li>
<li>The Member represents and warrants that (a) the recipient of any items shipped is the end user of any and all merchandise and mail that the Member requests be shipped to the recipient's address, (b) any and all merchandise and mail that the Member requests be shipped will be used in the country to which the Member requests shipment and (c) the Member will not re-export the merchandise and mail to a different destination. Shipville.com reserves the right to request that the Member or the recipient of an item, as applicable, sign documents confirming the end use or end user of any item shipped.</li>
<li>The Member is responsible for confirming that prohibited items listed in the Shipville.com Compliance Policy are not shipped to Shipville.com. Shipville.com reserves the right to return all packages to the sender(s) for any reason.</li>
<li>The Member represents and warrants that he/she will comply with all known applicable export and import control laws and regulations in its order and receipt of merchandise and mail under the terms of this Agreement.</li>
<li>The Member represents and warrants that all its activities will be conducted in compliance with applicable laws governing the export, import, and provision of goods and services in the United States and in the jurisdictions in which the Member resides, operates, or will receive shipments, including but not limited to the Laws of the United States governing embargoes, sanctions, and boycotts, the Arms Export Controls Act (22 U.S.C. 2778), the International Emergency Economic Powers Act (50 U.S.C. 1701 et seq.), the Export Administration Act of 1979 (50 U.S.C. app. 2401-2420), the International Traffic in Arms Regulations (22 C.F.R. 120 et seq.), the Export Administration Regulations (15 C.F.R. 730 et. seq.), the Foreign Trade Regulations (15 C.F.R. Part 30) and all rules, regulations and executive orders relating to any of the foregoing, the Laws administered by the Office of Foreign Assets Controls of the United States Department of the Treasury, the Laws administered by United States Customs and Border Protection, and the Laws administered by the Bureau of Alcohol, Tobacco, Firearms, and Explosives of the U.S. Department of Justice (collectively "Export, Import, and Economic Sanctions Laws")</li>
<li>At no time shall the Member provide merchandise or mail to any Prohibited Person (as defined herein). For purposes of this Agreement, a "Prohibited Person"ù shall mean (a) a Person who is a "designated national","specially designated national","especially designated terrorist","specially designated global terrorist","foreign terrorist organization","specially designated narcotics trafficker",ù or "blocked person"ù within the definitions set forth in the Foreign Assets Control Regulations of the United States Treasury Department, 31 C.F.R., Subtitle B, Chapter V, as amended (the "OFAC Regulations") or who otherwise appears on the list of Specially Designated Nationals and Blocked Persons, Appendix A to the OFAC Regulations; (b) the Government of Cuba, Iran, or Sudan, including any political subdivision, agency, or instrumentality thereof, or any other country against which the United States maintains economic sanctions or embargos under the OFAC Regulations or Executive Order; (c) a Person acting or purporting to act, directly or indirectly, on behalf of, or an entity owned or controlled by, any government, individual, or group against which the United States maintains economic sanctions or embargoes under the OFAC Regulations or Executive Order; (d) a Person who is described in section 1 of Executive Order 13224 ‚Äì Blocking Property and Prohibiting Transactions with Persons who Commit, Threaten to Commit, or Support Terrorism, effective September 24, 2001; (e) a Person on any other list of terrorists or terrorist organizations maintained pursuant to any of the rules or regulations of OFAC or pursuant to any other Executive Order; or (F) a Person in violation of any other law, regulation, or Executive Order of similar import, as each such law has been or may be amended, adjusted, or modified or reviewed from time to time. In the event that the Member is believed potentially to be a Prohibited Person or requests that Shipville.com ship items to an individual or entity believed to be a Prohibited Person, Shipville.com may ask the Member to provide documentation to show that the Member and/or individual or entity to which a request to ship items has been made is not a Prohibited Person. If the identity of the Member and/or the individual or entity to which a request to ship items has been made cannot be proven to the satisfaction of Shipville.com, Shipville.com reserves the right to remove the shipping address of such potential Prohibited Persons from the Member's account or to cancel the Member's account, Shipville.com also reserves the right to request a signed Statement of Assurance from the Member stating that the Member understands his or her obligations under U.S. export law and that the Member will conduct screening to ensure that the Member does not ship to Prohibited Persons through Shipville.com.</li></ul>
 
<h2>III. APPOINTMENT OF SHIPVILLE.COM AS MEMBER'S AGENT</h2>
 
<ul>
<li>As a Member, you grant Shipville.com a ‚ÄúLimited‚Äù Power of Attorney to act as your agent for the following specific purposes:
<ul>
<li>preparation of shipping documents;</li>
<li>preparation of any Certificates of Origin;</li>
<li>preparation of an EEI via AES and</li>
<li>preparation of an airway bill or any other document required to ship merchandise to Member.</li>
</ul></li>
<li>If an EEI (for which a $25 preparation charge will apply) or a Certificate of Origin (for which a $10 preparation charge will apply) is required for goods manufactured and originating within the United States, Shipville.com will file the required export information on behalf of the Member as its agent pursuant to this section.</li>
 
<li>The Member must acknowledge that he/she has a duty to "and is solely liable for" providing all information required by United States' laws and regulations, including information required by 15 CFR ¬ß 30 and maintaining all records as required under the customs or other government agency laws.</li>
 
<li>MyUS.com assumes no responsibility to act as a record-keeper or record-keeping agent for either the Member or the USPPI. The Member is responsible to supply to Shipville.com all information regarding the USPPI, including its name and employer identification number (EIN), and the Export Control Classification Number ("ECCN"ù), Schedule B classification and all other information required under a routed export transaction as described in Title 15, Code of Federal Regulations, Part 30, the Foreign Trade Regulations (FTSR).</li></ul>
 
<h2>IV. INDEMNIFICATION</h2>
<ul>
<li>The Member agrees that he/she will remain liable for and indemnify, defend, and hold harmless Shipville.com and its shareholders, officers, directors, agents, partners, employees and independent contractors, at all times from the date hereof forward, from and against any and all claims, actions, damages, awards, liabilities, losses (including consequential losses), judgments, penalties, interest, fines, expenses, and/or other costs (including attorneys' charges and court costs) arising by reason of the execution hereof or the consummation of the transactions contemplated hereby, including without limitation those arising from or relating to:<ul>
<li>any negligent action or omission of Member or any of the Member's employees, contractors, agents or any other person acting under Member's supervision or control prior to, as of, or following the date hereof;</li>
<li>any inaccuracy or breach of any representation or warranty made by Member in this Agreement or any other document or instrument executed or delivered by Member in connection with this Agreement;</li>
<li>any breach or non-performance of any covenant or agreement made by Company in this Agreement or any other document or instrument made by Member in connection with this Agreement;</li>
<li>Shipville.com's preparation, determination or execution of the documents (including international air waybills) or any other document necessary for transportation, including but not limited to preparing address information, routing, classification, licensing requirements, and listing the value of goods or the value for carriage, except for claims arising solely from the gross negligence or willful misconduct of Shipville.com;</li>
<li>the Member providing to Shipville.com any incomplete or false information; and</li>
<li>the Member's failure to comply with the terms hereof or of any jurisdiction's law applicable to the exportation or importation of such shipments.</li>
<li>The Member acknowledges that the foregoing provisions are a material inducement for Shipville.com to enter into this Agreement and the transactions contemplated hereby, and shall survive termination of this Agreement.</ul></li>
</ul>

<h2>COMPLIANCE POLICY</h2>
 
Shipville.com will not directly or indirectly, participate in any way in any transaction involving any commodity, software or technology (hereinafter collectively referred to as "item") exported or to be exported from the United States that is subject to theInternational Trade in Arms Regulations (ITAR) or that would require an export license under the Export Administration Regulations (EAR). MyUS.com takes every precaution and makes every effort to fully comply with all laws and regulations governing international trade, including the Federal Trade Statistics Regulations (FTSR).
 <br><br>
I. Prohibited and Restricted Items<br>
The following list is a non-exclusive sampling of items that are either restricted, cannot be shipped or, depending on your destination country, may either require an import license, additional documentation and/or cause problems and delays during the customs review of your shipment:
<ul> 
<li>Combustible/flammable items (paints, oils, lighters, perfume, nail polish)</li>
<li>Any type of pressurized can (hair spray, shaving cream, spray cans of any type)</li>
<li>Hazardous materials (matches, chemicals, explosives)</li>
<li>Firearms, weaponry and their parts: military, police and tactical equipment of any kind, including guns, gun replicas, gun accessories, gun components (magazines, clips and rail systems), ammunition, knives, swords, compound bows, crossbows, discharge weapons such as shock batons or stun guns, tooling for guns or gun parts, optical scopes, laser sights, night sights, night visions goggles, handcuffs and other restraints, surveillance equipment</li>
<li>Agricultural products such as tobacco, plants and seeds (restricted to some destinations)</li>
<li>Coffee (restricted to some destinations)</li>
<li>Perishable foods (restricted to some destinations)</li>
<li>Animals and products made with animal skin (furs)</li>
<li>Alcohol (MyUS.com can ship table wine in limited quantities to most countries except Muslim countries such as Saudi Arabia)</li>
<li>Cash, currency, money orders, cashiersí checks, bank drafts, bearer bonds and collectible stamps and coins. Jewelry and precious stones are (a) restricted to some countries and (b) can only be insured up to $500 maximum and any shipments of jewelry in excess of $500 carriage limit is uninsured and Member assumes all risk of loss above such limit</li>
<li>Lottery tickets and gambling devices</li>
<li>Prescription and/or veterinary medication</li>
<li>Pornography</li>
<li>Lock picking devices</li>
<li>Government IDs and licenses, or items that claim to be, or that look similar to, government identification documents. This includes uniforms and badges or patches designed to look like official government-issue.</li>
</ul>
<br>
Member understands and agrees that any software and/or data residing on used computer equipment or other electronic storage device is the sole responsibility of the Member. The Member is responsible for and warrants his/her compliance with all applicable import and export laws, rules and regulations, including, but not limited to, the import and export laws and government regulations Office of Foreign Assets Control, U.S. Department of State, and U.S. Department of Commerce requirements pertaining to the shipping of any such software and/or data to any country to, from, through or over which the Member's shipment may be carried.  Member also understands that Shipville.com is not responsbile for the loss of any software and/or data. 
 <br><br>
II. Countries Shipville.com Does Not Ship To<br>
Shipville.com will not ship to any of the following countries:
<ul>
<li>Cuba</li>
<li>Iran</li>
<li>Myanmar</li>
<li>North Korea</li>
<li>Sudan</li>
<li>Syria</li>
 </ul>
 <br>
III. Fraud Prevention<br>
Shipville.com will use commercially reasonable best efforts to prevent any fraudulent use of the Shipville.com service. Shipville.com works diligently to prevent credit card fraud and cancels any Member accounts engaged in such activity and returns the merchandise to the merchant. Shipville.com requires documentation from applicants to ensure against fraud, such as requiring copies of identification and credit cards. Shipville.com also prohibits use of the Shipville.com service for multi-level marketing, pyramid schemes, receiving checks and/money orders, and other business practices easily subject to abuse.
 <br><br>
IV. Denied Persons<br>
Shipville.com will not ship to persons and/or entities identified on: (1) the U.S. Department of Commerce Denied Persons List,Entity List of proliferation concern, or Unverified List; (2) the U.S. State Department Debarred Parties List; or (3) the List of Specially Designated Nationals maintained by the U.S. Department of the Treasury's Office of Foreign Assets Control. Shipville.com also will not ship to any person or entity that is directly or indirectly involved in the financing, commission or support of terrorist activities or in the development or production of nuclear, chemical, biological weapons or in missile technology programs as specified in the U.S. Export Administration Regulations (15 C.F.R. part 744).